name: Deployment Pipeline for master branch
on:
  push:
    branches:
      - master
jobs:
  deploy:
    permissions: write-all
    runs-on: windows-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    
    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up .NET
      id: setup
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '8.x'
        
    - name: Build .NET solution
      id: build
      run: |
        dotnet build gamevault.sln --configuration Release
        7z a GameVault.zip gamevault/bin

    - name: Upload Action Artifact
      uses: actions/upload-artifact@v4
      with:
        path: GameVault.zip
        compression-level: 9
        retention-days: 90

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: GameVault.zip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        

